spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "*"
                allowed-headers: "*"
                allowed-methods: "*"
                allow-credentials: false
          routes:
            - id: catalog-service
              uri: ${CATALOG_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/catalog/**
              filters:
                - RewritePath=/catalog/?(?<segment>.*), /${segment}
            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/order/**
              filters:
                - RewritePath=/order/?(?<segment>.*), /${segment}
            - id: open-api
              uri: http://localhost:${server.port}
              predicates:
                - Path=/v3/api-docs/**
              filters:
                - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs
          filter:
            dedupe-response-header:
              enabled: true
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_FIRST
  mvc:
    problemdetails:
      enabled: true
server:
  port: 8080
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    git:
      mode: full
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1

springdoc:
  swagger-ui:
    use-root-path: true
#    urls:
#      - name: catalog
#        url: /v3/api-docs/catalog
