name: microservices-practice-2

services:
  catalog-service:
    container_name: catalog-service
    image: ghcr.io/thivernale/catalog-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://bookstore-db:5432/catalog-service
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      APP_URLS_API-GATEWAY: http://api-gateway:8080
      MANAGEMENT_TRACING_ENABLED: true
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://bookstore-tempo:9411
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      bookstore-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  order-service:
    container_name: order-service
    image: ghcr.io/thivernale/order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      ORDERS_CATALOG-SERVICE-URL: http://api-gateway:8080/catalog
      DB_URL: jdbc:postgresql://bookstore-db:5432/order-service
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: bookstore-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      APP_URLS_API-GATEWAY: http://api-gateway:8080
      APP_URLS_OAUTH2-SERVER: http://keycloak:8180
      MANAGEMENT_TRACING_ENABLED: true
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://bookstore-tempo:9411
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      bookstore-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1000m
    labels:
      logging: "promtail"

  notification-service:
    container_name: notification-service
    image: ghcr.io/thivernale/notification-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://bookstore-db:5432/notification-service
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RABBITMQ_HOST: bookstore-rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MAIL_HOST: bookstore-mailhog
      MAIL_PORT: 1025
      MANAGEMENT_TRACING_ENABLED: true
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://bookstore-tempo:9411
    ports:
      - "8083:8083"
    restart: unless-stopped
    depends_on:
      bookstore-db:
        condition: service_healthy
      bookstore-rabbitmq:
        condition: service_healthy
      bookstore-mailhog:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  api-gateway:
    container_name: api-gateway
    image: ghcr.io/thivernale/api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CATALOG_SERVICE_URL: http://catalog-service:8081
      ORDER_SERVICE_URL: http://order-service:8082
      MANAGEMENT_TRACING_ENABLED: true
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://bookstore-tempo:9411
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"
