name: microservices-practice-2

services:
  bookstore-db:
    container_name: bookstore-db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #      POSTGRES_DB: catalog-service
      PGDATA: /data/postgres
    volumes:
      #      - ./db:/data/postgres
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    ports:
      - "5432:5432"
    #    networks:
    #      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  bookstore-rabbitmq:
    container_name: bookstore-rabbitmq
    image: 'rabbitmq:4.1.0-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

#networks:
#  db:
#    driver: bridge
#
#volumes:
#  db:
#    driver: local
