name: microservices-practice-2

services:
  bookstore-db:
    container_name: bookstore-db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #      POSTGRES_DB: catalog-service
      PGDATA: /data/postgres
    volumes:
      - 'db-data:/data/postgres'
      - './postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro'

    ports:
      - "5432:5432"
    #    networks:
    #      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  bookstore-rabbitmq:
    container_name: bookstore-rabbitmq
    image: rabbitmq:4.1.0-management
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  bookstore-mailhog:
    container_name: bookstore-mailhog
    image: mailhog/mailhog:v1.0.1
    ports:
      - '1025:1025'
      - '8025:8025'
    deploy:
      resources:
        limits:
          memory: 100m

  bookstore-keycloak:
    container_name: bookstore-keycloak
    image: quay.io/keycloak/keycloak:26.2
    environment:
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: 'admin'
      KC_BOOTSTRAP_ADMIN_PASSWORD: 'admin'
      KC_DB: dev-file
    ports:
      - '8180:8080'
    volumes:
      - 'keycloak-data:/opt/keycloak/data'
      - './keycloak:/opt/keycloak/data/import'
    command:
      - 'start-dev'
      - '--import-realm'
      - '--db=dev-file'
    deploy:
      resources:
        limits:
          memory: 1000m

#networks:
#  db:
#    driver: bridge
#
volumes:
  db-data:
    driver: local
  keycloak-data:
    driver: local
