name: microservices-practice-2

services:
  catalog-db:
    container_name: catalog-db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog-service
      PGDATA: /data/postgres
#    volumes:
#      - ./db:/data/postgres
    ports:
      - "5432:5432"
#    networks:
#      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

#networks:
#  db:
#    driver: bridge
#
#volumes:
#  db:
#    driver: local
